version: '3.4'

services:
  jimple-framework:
    container_name: my-jimple-framework
    image: jimple-framework
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /usr/app/jimpleFramework 
    volumes:
        - ./app:/usr/app
    ports:
      - 3010:3000
    command: tail -f /dev/null # keep open container 
